#paste the given below content in Vagrantfile
Vagrant.configure("2") do |config|
    #config.vm.box = "base"
  
    config.vm.define "web" do |web|
      web.vm.provider "virtualbox" do |vb_web|
        vb_web.memory = 1024
        vb_web.cpus = 2
      end
  
      web.vm.box = "ubuntu/bionic64"
      web.vm.hostname = "web01"
      web.vm.network "private_network", ip: "192.168.56.10"
  
    end
  
    config.vm.define "mysql" do |mysql|
      mysql.vm.box = "ubuntu/bionic64"
      mysql.vm.hostname = "mysql01"
      mysql.vm.network "private_network", ip: "192.168.56.11"
  
    end
  